# Generated by Django 3.2.1 on 2021-05-12 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210513_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccnjobcard',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.division'),
        ),
    ]
