# Generated by Django 3.2.1 on 2021-05-12 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_ccnjobcard_division'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemcategory',
            options={'verbose_name': 'problemcategory', 'verbose_name_plural': 'problemcategories'},
        ),
        migrations.AddField(
            model_name='ccnjobcard',
            name='problemcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.problemcategory'),
        ),
    ]
