# Generated by Django 3.2.1 on 2021-05-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_engineer_name_ccnjobcard_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccnjobcard',
            name='engg_comment',
            field=models.CharField(default=False, max_length=50, null=True),
        ),
    ]
