# Generated by Django 3.2.1 on 2021-05-14 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210514_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(blank=True, max_length=50, null=True)),
                ('p_model', models.CharField(blank=True, max_length=50, null=True)),
                ('p_sr_no', models.CharField(blank=True, max_length=50, null=True)),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.problemcategory')),
            ],
        ),
        migrations.RemoveField(
            model_name='ccnjobcard',
            name='city',
        ),
        migrations.RemoveField(
            model_name='ccnjobcard',
            name='country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
