# Generated by Django 3.2.1 on 2021-05-14 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210514_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer',
            name='p_model',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='p_sr_no',
        ),
    ]
