# Generated by Django 3.2.1 on 2021-05-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210514_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_pic',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ccnjobcard',
            name='assigned_to',
            field=models.CharField(default='Not Assigned', max_length=50, null=True),
        ),
    ]
