# Generated by Django 3.2.3 on 2021-05-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210519_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccnjobcard',
            name='sr_no',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
