# Generated by Django 3.2.3 on 2021-05-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_ccnjobcard_sr_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccnjobcard',
            name='model_no',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
