# Generated by Django 3.2.3 on 2021-05-19 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210519_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternetJobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=30, null=True)),
                ('ccn_internet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ccnjobcard')),
            ],
        ),
    ]
