# Generated by Django 3.2.3 on 2021-05-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_internetjobcard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printerjobcard',
            old_name='sr_no',
            new_name='printer_make',
        ),
        migrations.AddField(
            model_name='printerjobcard',
            name='printer_problem',
            field=models.TextField(max_length=512, null=True),
        ),
    ]
