# Generated by Django 3.2.3 on 2021-05-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_rename_printer_problem_printerjobcard_problem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internetjobcard',
            name='issue',
        ),
        migrations.AddField(
            model_name='internetjobcard',
            name='issue_in',
            field=models.CharField(blank=True, choices=[('LAN', 'LAN'), ('Wi-Fi', 'Wi-Fi')], max_length=10),
        ),
        migrations.AddField(
            model_name='internetjobcard',
            name='problem',
            field=models.TextField(max_length=512, null=True),
        ),
    ]
