# Generated by Django 3.2.3 on 2021-06-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20210520_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccnjobcard',
            name='closed_by_user_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
