# Generated by Django 3.2.3 on 2021-06-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_ccnjobcard_closed_by_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccnjobcard',
            name='job_on',
            field=models.CharField(blank=True, choices=[('User Head', 'User Head'), ('CCN Head', 'CCN Head'), ('Engineer', 'Engineer'), ('Customer', 'Customer')], default='User Head', max_length=10),
        ),
    ]
